# Site settings
title: aauthor
email: apocryphalauthor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The life an history of Tom Dunlap.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "aauthor.github.io" # the base hostname & protocol for your site
twitter_username: aauthor
github_username:  aauthor

# Build settings
markdown: kramdown
