# Site settings
title: Loose Pages
email: tom@aauthor.space
description: > # this means to ignore newlines until "baseurl:"
  notes and null pointers
baseurl: "" # the subpath of your site, e.g. /blog/
url: "aauthor.space" # the base hostname & protocol for your site
twitter_username: aauthor
github_username:  aauthor

# Build settings
markdown: kramdown
