# Site settings
title: Loose Pages
email: apocryphalauthor@gmail.com
description: "notes and null pointers"
baseurl: ""
url: "aauthor.github.io"
twitter_username: aauthor
github_username: aauthor
disqus_username: false
isso_domain: false

# Build settings
markdown: redcarpet
permalink: /:title/
excerpt_separator: "<!--more-->"

defaults:
  -
    scope:
      path: ""
    values:
      author: "Tom Dunlap"
      layout: "default"
